"""elapsed time kind

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 15:45:24.182109
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rows extracted before this column existed only held forward jumps.
    op.add_column(
        "elapsed_time_facts",
        sa.Column("kind", sa.String(length=16), nullable=False, server_default="advance"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("elapsed_time_facts", "kind")
    # ### end Alembic commands ###
