"""issue subjects

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 15:59:28.697535
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Issues created before this column existed get an empty subject list.
    op.add_column(
        "consistency_issues",
        sa.Column(
            "subjects",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default="[]",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consistency_issues", "subjects")
    # ### end Alembic commands ###
