"""age ranges speculative offset quote

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 17:30:55.861387
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("age_facts", sa.Column("value_max", sa.Float(), nullable=True))
    # Facts extracted before this column existed were all taken as stated facts.
    op.add_column(
        "age_facts",
        sa.Column("is_speculative", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("age_facts", sa.Column("years_before_present_quote", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("age_facts", "years_before_present_quote")
    op.drop_column("age_facts", "is_speculative")
    op.drop_column("age_facts", "value_max")
    # ### end Alembic commands ###
