"""issue resolved_from

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-27 12:04:07.938655
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consistency_issues", sa.Column("resolved_from", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consistency_issues", "resolved_from")
    # ### end Alembic commands ###
